version: '3.1'
services:
  eureka1:
    image: akiraliu/eureka
    container_name: euerka1
    ports:
      - 9002:9002
    expose:
      - 9002
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
    networks:
      hx_net:
        ipv4_address: 172.19.0.2

  eureka2:
    image: akiraliu/eureka
    container_name: euerka2
    ports:
      - 9003:9003
    expose:
      - 9003
    environment:
      - SPRING_PROFILES_ACTIVE=peer2
    networks:
      hx_net:
        ipv4_address: 172.19.0.3

networks:
  hx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16