spring:
  application:
    name: admin-server
  security:
    user:
      name: user-admin
      password: admin_pass
server:
  port: 9901



eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user.name: user-admin
      user.password: admin_pass
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://wxuser:123456@localhost:9001/eureka



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS